FROM openjdk:8
EXPOSE 8091
ADD target/PPP-ReclamationMicroService-0.0.1-SNAPSHOT.jar PPP-ReclamationMicroService-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "/PPP-ReclamationMicroService-0.0.1-SNAPSHOT.jar"]