FROM openjdk:8
EXPOSE 8094
ADD target/PPP-PharmacieMicroService-0.0.1-SNAPSHOT.jar PPP-PharmacieMicroService-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "/PPP-PharmacieMicroService-0.0.1-SNAPSHOT.jar"]